"""empty message

Revision ID: 7f2945cea63c
Revises: c735ff660c29
Create Date: 2017-05-28 20:47:02.129784

"""

# revision identifiers, used by Alembic.
revision = '7f2945cea63c'
down_revision = 'c735ff660c29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
